/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

import conexion.ConexionBD;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAMILIA S
 */
public class Entregas extends javax.swing.JInternalFrame {
 ConexionBD cone;
    DefaultTableModel modelo;
    public Entregas() {
        initComponents();
        cone = new ConexionBD();
        String[] columnNames = {"codigo", "fecha", "hora", "metodopago", "total", "cedula_usuario", "num_doc_domiciliario", "estado", "direccion_envio", "observacion_pedido", "observacion_entrega"};
        modelo = new DefaultTableModel(null, columnNames);
        consultar();
        this.setSize(new Dimension(1181, 526));

        this.setMinimumSize(new Dimension(1181, 526));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_dinero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txt_obvs = new javax.swing.JTextField();
        bto_actualizar = new javax.swing.JButton();
        bto_enviar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1163, 532));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GESTIÓN DE ENTREGAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(67, 67, 67))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1170, 193);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dinero pago");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(106, 261, 76, 20);

        txt_dinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dineroKeyTyped(evt);
            }
        });
        jPanel2.add(txt_dinero);
        txt_dinero.setBounds(188, 261, 106, 22);

        jButton1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jButton1.setText("Depositar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(312, 258, 89, 27);

        jScrollPane1.setHorizontalScrollBar(null);

        tabla.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jScrollPane3.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(41, 103, 1129, 137);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Código");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 20, 65, 26);

        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_codigo);
        txt_codigo.setBounds(120, 20, 100, 30);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estado");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(300, 20, 53, 30);

        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });
        txt_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_estadoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_estado);
        txt_estado.setBounds(360, 20, 99, 30);

        jTextField1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jTextField1.setText("Observaciones");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(470, 20, 116, 30);

        txt_obvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_obvsActionPerformed(evt);
            }
        });
        txt_obvs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_obvsKeyTyped(evt);
            }
        });
        jPanel2.add(txt_obvs);
        txt_obvs.setBounds(630, 20, 261, 30);

        bto_actualizar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        bto_actualizar.setText("Actualizar");
        bto_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(bto_actualizar);
        bto_actualizar.setBounds(500, 60, 120, 27);

        bto_enviar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        bto_enviar.setText("Enviar");
        bto_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_enviarActionPerformed(evt);
            }
        });
        jPanel2.add(bto_enviar);
        bto_enviar.setBounds(900, 20, 72, 27);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-40, 190, 1210, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void bto_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_actualizarActionPerformed
   cone.modificaDatos("UPDATE pedidos SET estado='" + txt_estado.getText() + "' WHERE codigo=" + txt_codigo.getText());
        consultar();    }//GEN-LAST:event_bto_actualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cone.modificaDatos("UPDATE pedidos SET total='" + txt_dinero.getText() + "' WHERE codigo=" + txt_codigo.getText());
        consultar();       }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_obvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_obvsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_obvsActionPerformed

    private void bto_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_enviarActionPerformed
cone.modificaDatos("UPDATE pedidos SET observacion_entrega='" + txt_obvs.getText() + "' WHERE codigo=" + txt_codigo.getText());
        consultar();      }//GEN-LAST:event_bto_enviarActionPerformed

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
 char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();   
    }//GEN-LAST:event_txt_codigoKeyTyped

    private void txt_dineroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dineroKeyTyped
 char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();       }//GEN-LAST:event_txt_dineroKeyTyped

    private void txt_estadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_estadoKeyTyped
char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A') | c > 'Z')
            evt.consume();
    }//GEN-LAST:event_txt_estadoKeyTyped

    private void txt_obvsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_obvsKeyTyped
char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A') | c > 'Z')
            evt.consume();    }//GEN-LAST:event_txt_obvsKeyTyped

 public void consultar() {
        try {
            ResultSet rs1 = cone.consultaDatos("SELECT * FROM pedidos");
            String[] columnNames = {"codigo", "fecha", "hora", "metodopago", "total", "cedula_usuario", "num_doc_domiciliario", "estado", "direccion_envio", "observacion_pedido", "observacion_entrega"};
            modelo = new DefaultTableModel(null, columnNames);
            String[] datos = new String[11];
            while (rs1.next()) {
                datos[0] = rs1.getString("codigo");
                datos[1] = rs1.getString("fecha");
                datos[2] = rs1.getString("hora");
                datos[3] = rs1.getString("metodopago");
                datos[4] = rs1.getString("total");
                datos[5] = rs1.getString("cedula_usuario");
                datos[6] = rs1.getString("num_doc_domiciliario");
                datos[7] = rs1.getString("estado");
                datos[8] = rs1.getString("direccion_envio");
                datos[9] = rs1.getString("observacion_pedido");
                datos[10] = rs1.getString("observacion_entrega");
                modelo.addRow(datos);
            }
            tabla.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Gestion_roles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_actualizar;
    private javax.swing.JButton bto_enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_dinero;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_obvs;
    // End of variables declaration//GEN-END:variables
}
