/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

import conexion.ConexionBD;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.*;



/**
 *
 * @author FAMILIA S
 */
public class Report extends javax.swing.JInternalFrame {

   ConexionBD cone;
    DefaultTableModel modelo;
    Connection conn=null;
    public Report() {
        initComponents();
        cone = new ConexionBD();
        String[] columnNames = {"mes","venta_dias","dias_trabajados","total"};
        modelo = new DefaultTableModel(null, columnNames);
        consultar();
        this.setSize(new Dimension(716, 338));

        this.setMinimumSize(new Dimension(716, 338));
        
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_mes = new javax.swing.JTextField();
        txt_ventas = new javax.swing.JTextField();
        txt_dias = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bto_pdf = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ventas por dias");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(54, 205, 100, 20);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dias trabajados");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(54, 239, 100, 20);

        txt_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mesActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mes);
        txt_mes.setBounds(160, 168, 127, 22);

        txt_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ventasActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ventas);
        txt_ventas.setBounds(160, 202, 127, 22);

        txt_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diasActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dias);
        txt_dias.setBounds(160, 236, 127, 22);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 0, 710, 140);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 276, 90, 23);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(329, 168, 286, 127);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(54, 171, 100, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bto_pdf.setText("Mostrar en pdf");
        bto_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_pdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(bto_pdf)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(bto_pdf)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 140, 710, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total=0;
        total=Integer.parseInt(txt_ventas.getText())*Integer.parseInt(txt_dias.getText());

        cone.modificaDatos("INSERT INTO venta1 VALUES('"  + txt_mes.getText()+"','"+txt_ventas.getText()+"','"+txt_dias.getText()+"','"+total+"')");
        consultar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ventasActionPerformed

    private void txt_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diasActionPerformed

    private void bto_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_pdfActionPerformed
try{
Class.forName("com.mysql.jdbc.Driver");

conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/arepapp","root","");
JasperDesign jdesign = JRXmlLoader.load("D:\\Perfil FamiliaS\\Documents\\c\\ArepApp\\src\\Report\\report1.jrxml");

String query = "SELECT * FROM venta1";

JRDesignQuery updateQuery = new JRDesignQuery();

updateQuery.setText(query);

jdesign.setQuery(updateQuery);

JasperReport jreport = JasperCompileManager.compileReport(jdesign);

JasperPrint jprint = JasperFillManager.fillReport(jreport, null,conn);

JasperViewer.viewReport(jprint);

JOptionPane.showMessageDialog(null,"Conexiónestablecida");
}
 catch(Exception ex)
 {
  ex.printStackTrace();
 }
    }//GEN-LAST:event_bto_pdfActionPerformed
public void consultar() {
        try {
            ResultSet rs1 = cone.consultaDatos("SELECT * FROM venta1");
            String[] columnNames = {"mes","ventas_dia","dias_trabajados","total"};
            modelo = new DefaultTableModel(null, columnNames);
            String[] datos = new String[4];
            while (rs1.next()) {
                datos[0] = rs1.getString("mes");
                datos[1] = rs1.getString("ventas_dia");
                 datos[2] = rs1.getString("dias_trabajados");
                  datos[3] = rs1.getString("total");
                modelo.addRow(datos);
            }
            tabla.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Gestion_roles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_pdf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_dias;
    private javax.swing.JTextField txt_mes;
    private javax.swing.JTextField txt_ventas;
    // End of variables declaration//GEN-END:variables
}
